site_name: Mythic Metals Wiki
site_url: https://wiki.mythicmetals.dev
theme:
    name: null
    custom_dir: mkdocs-material/material
    palette:
        - scheme: slate
          primary: indigo
          accent: blue  
          toggle:
            icon: material/brightness-4
            name: Switch to light mode

        - scheme: default
          primary: indigo
          accent: blue
          toggle:
            icon: material/brightness-7 
            name: Switch to dark mode
    features:
        navigation.tabs
        navigation.indexes
        navigation.expand
        search.suggest
        search.share
        navigation.top
        content.code.annotate
    favicon: assets/favicon.png
    icon:
      logo: octicons/flame-16 
    language: en
    font:
        text: Fira Sans
        code: Fira Mono

copyright: "Documentation by <a style=\"color: #13A6F0;\" href=\"https://github.com/Noaaan\">Noaaan</a>, with assistance from glisco, the Wisp Forest team, and the Wraith Coding Sesh crew"
extra:          
  social:
    - icon: fontawesome/brands/discord
      link: https://discord.gg/xrwHKktV2d
    - icon: fontawesome/brands/github
      link: https://github.com/wisp-forest/
  projects:
      mythicmetals:
          repo: https://github.com/Noaaan/MythicMetals
          name: Mythic Metals
          icon: owo.png
      mythicmetalsdecorations:
          repo: https://github.com/Noaaan/MythicMetalsDecorations
          name: Mythic Metals Decorations
          icon: owo.png
      docs:
          repo: https://github.com/Noaaan/docs
          name: Mythic Metals Wiki

extra_css:
    - overrides.css

plugins:
  - search
  - git-revision-date-localized:
      type: timeago

markdown_extensions:
    - admonition
    - attr_list
    - pymdownx.tasklist:
        custom_checkbox: true
    - pymdownx.details
    - pymdownx.keys
    - pymdownx.arithmatex:
        generic: true
    - pymdownx.highlight:
        anchor_linenums: true
    - pymdownx.inlinehilite
    - pymdownx.snippets
    - footnotes
    - pymdownx.superfences:
        custom_fences:
          - name: mermaid
            class: mermaid
            format: !!python/name:pymdownx.superfences.fence_code_format
    - pymdownx.tabbed:
        alternate_style: true
    - toc:
        permalink: true
    - pymdownx.emoji:
        emoji_index: !!python/name:materialx.emoji.twemoji
        emoji_generator: !!python/name:materialx.emoji.to_svg
    - pymdownx.tilde
    - pymdownx.critic

nav:
    - Home: 
        - index.md
    - MythicMetals:
        - home.md

